### ISSUE TITLE
Deployment App Service fails with "The request was aborted"

### ISSUE THREAD

**Issue by Camble** [microsoft/vscode-node-azure-pack#38]
Extension version: 1.0.0

Every time I try to deploy to an Azure App Service, I get the error: "The request was aborted"

```
16:55:43 AppService: Starting deployment...
16:55:58 AppService: Creating zip package...
16:56:58 AppService: Zip package size: 166 MB
16:57:21: Error: The request was aborted
```

Originally reported here: https://github.com/microsoft/vscode/issues/156724 but closed.

**Comment by alexweininger** [comment]
Thanks for reporting this issue, we're tracking this on the Azure App Service extension for VS Code repo https://github.com/microsoft/vscode-azureappservice/issues/2305.

**Comment by KartikeyBartwal** [comment]
I don't think the issue is solved yet. I faced the same error when I was trying to deploy my fastapi on azure via vs code

14:14:49 testing911: Starting deployment...
14:14:49 testing911: Creating zip package...
14:14:49 testing911: Ignoring files from "appService.zipIgnorePattern"
"__pycache__{,/**}"
"*.py[cod]"
"*$py.class"
".Python{,/**}"
"build{,/**}"
"develop-eggs{,/**}"
"dist{,/**}"
"downloads{,/**}"
"eggs{,/**}"
".eggs{,/**}"
"lib{,/**}"
"lib64{,/**}"
"parts{,/**}"
"sdist{,/**}"
"var{,/**}"
"wheels{,/**}"
"share/python-wheels{,/**}"
"*.egg-info{,/**}"
".installed.cfg"
"*.egg"
"MANIFEST"
".env{,/**}"
".venv{,/**}"
"env{,/**}"
"venv{,/**}"
"ENV{,/**}"
"env.bak{,/**}"
"venv.bak{,/**}"
".vscode{,/**}"
14:15:08 testing911: Zip package size: 23.7 MB
14:15:13 testing911: Fetching changes.
14:15:14 testing911: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/7f78c714-d5e3-4fc5-90b7-d13b624eee65.zip (22.59 MB) to /tmp/zipdeploy/extracted
14:15:18 testing911: Updating submodules.
14:15:19 testing911: Preparing deployment for commit id '9ec9808a-3'.
14:15:20 testing911: PreDeployment: context.CleanOutputPath False
14:15:20 testing911: PreDeployment: context.OutputPath /home/site/wwwroot
14:15:20 testing911: Repository path is /tmp/zipdeploy/extracted
14:15:20 testing911: Running oryx build...
14:15:20 testing911: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9 -p virtualenv_name=antenv --log-file /tmp/build-debug.log  -i /tmp/8dc294b72889797 --compress-destination-dir | tee /tmp/oryx-build.log
14:15:22 testing911: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
14:15:22 testing911: You can report issues at https://github.com/Microsoft/Oryx/issues
14:15:22 testing911: Oryx Version: 0.2.20230508.1, Commit: 7fe2bf39b357dd68572b438a85ca50b5ecfb4592, ReleaseTagName: 20230508.1
14:15:22 testing911: Build Operation ID: bff2f1647b08f9e9
14:15:22 testing911: Repository Commit : 9ec9808a-316d-458f-bb5d-04a6d397614e
14:15:22 testing911: OS Type           : buster
14:15:22 testing911: Image Type        : githubactions
14:15:22 testing911: Detecting platforms...
14:15:27 testing911: Detected following platforms:
14:15:28 testing911:   python: 3.9.18
14:15:28 testing911: Version '3.9.18' of platform 'python' is not installed. Generating script to install it...
14:15:29 testing911: Using intermediate directory '/tmp/8dc294b72889797'.
14:15:29 testing911: Copying files to the intermediate directory...
14:15:29 testing911: Done in 0 sec(s).
14:15:29 testing911: Source directory     : /tmp/8dc294b72889797
14:15:29 testing911: Destination directory: /home/site/wwwroot
14:15:30 testing911: Downloading and extracting 'python' version '3.9.18' to '/tmp/oryx/platforms/python/3.9.18'...
14:15:30 testing911: Detected image debian flavor: buster.
14:15:30 testing911: Downloaded in 2 sec(s).
14:15:30 testing911: Verifying checksum...
14:15:30 testing911: Extracting contents...
14:15:43 testing911: performing sha512 checksum for: python...
14:15:44 testing911: Done in 16 sec(s).
14:15:45 testing911: Python Version: /tmp/oryx/platforms/python/3.9.18/bin/python3.9
14:15:45 testing911: Creating directory for command manifest file if it does not exist
14:15:45 testing911: Removing existing manifest file
14:15:45 testing911: Python Virtual Environment: antenv
14:15:45 testing911: Creating virtual environment...
14:16:03 testing911: Activating virtual environment...
14:16:03 testing911: Running pip install...
14:20:48: Creating resource group "appsvc_linux_centralus_premium" in location "Central US"...
14:20:53: Successfully created resource group "appsvc_linux_centralus_premium".
14:20:53: Ensuring App Service plan "appsvc_linux_centralus_premium" exists...
14:20:53: Creating App Service plan "appsvc_linux_centralus_premium"...
14:20:58: Error: This region has quota of 0 PremiumV2 instances for your subscription. Try selecting different region or SKU.
14:21:55: Creating resource group "appsvc_linux_centralus_basic" in location "Central US"...
14:22:00: Successfully created resource group "appsvc_linux_centralus_basic".
14:22:00: Ensuring App Service plan "appsvc_linux_centralus_basic" exists...
14:22:01: Creating App Service plan "appsvc_linux_centralus_basic"...
14:22:08: Successfully created App Service plan "appsvc_linux_centralus_basic".
14:22:08: Verifying that Application Insights is available for this location...
14:22:09: Creating Application Insights resource "miketesting911"...
14:22:12: Successfully created Application Insights resource "miketesting911".
14:22:12: Creating new web app "miketesting911"...
14:22:33: Created new web app "miketesting911": https://miketesting911.azurewebsites.net
14:22:41 miketesting911: Starting deployment...
14:22:41 miketesting911: Creating zip package...
14:22:41 miketesting911: Ignoring files from "appService.zipIgnorePattern"
"__pycache__{,/**}"
"*.py[cod]"
"*$py.class"
".Python{,/**}"
"build{,/**}"
"develop-eggs{,/**}"
"dist{,/**}"
"downloads{,/**}"
"eggs{,/**}"
".eggs{,/**}"
"lib{,/**}"
"lib64{,/**}"
"parts{,/**}"
"sdist{,/**}"
"var{,/**}"
"wheels{,/**}"
"share/python-wheels{,/**}"
"*.egg-info{,/**}"
".installed.cfg"
"*.egg"
"MANIFEST"
".env{,/**}"
".venv{,/**}"
"env{,/**}"
"venv{,/**}"
"ENV{,/**}"
"env.bak{,/**}"
"venv.bak{,/**}"
".vscode{,/**}"
14:23:12 miketesting911: Zip package size: 23.7 MB
14:23:16 miketesting911: Fetching changes.
14:23:17 miketesting911: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/8fd05fbd-2ae3-4fce-8b35-cdd6934738ca.zip (22.59 MB) to /tmp/zipdeploy/extracted
14:23:23 miketesting911: Updating submodules.
14:23:24 miketesting911: Preparing deployment for commit id '491d7721-8'.
14:23:24 miketesting911: PreDeployment: context.CleanOutputPath False
14:23:24 miketesting911: PreDeployment: context.OutputPath /home/site/wwwroot
14:23:24 miketesting911: Repository path is /tmp/zipdeploy/extracted
14:23:24 miketesting911: Running oryx build...
14:23:24 miketesting911: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9 -p virtualenv_name=antenv --log-file /tmp/build-debug.log  -i /tmp/8dc294c9322c9f9 --compress-destination-dir | tee /tmp/oryx-build.log
14:23:27 miketesting911: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
14:23:27 miketesting911: You can report issues at https://github.com/Microsoft/Oryx/issues
14:23:27 miketesting911: Oryx Version: 0.2.20230508.1, Commit: 7fe2bf39b357dd68572b438a85ca50b5ecfb4592, ReleaseTagName: 20230508.1
14:23:27 miketesting911: Build Operation ID: 4a06482ffcf929ea
14:23:27 miketesting911: Repository Commit : 491d7721-84d5-4be9-a9ec-61ea8b600109
14:23:27 miketesting911: OS Type           : buster
14:23:27 miketesting911: Image Type        : githubactions
14:23:27 miketesting911: Detecting platforms...
14:23:29 miketesting911: Detected following platforms:
14:23:29 miketesting911:   python: 3.9.18
14:23:29 miketesting911: Version '3.9.18' of platform 'python' is not installed. Generating script to install it...
14:23:30 miketesting911: Using intermediate directory '/tmp/8dc294c9322c9f9'.
14:23:30 miketesting911: Copying files to the intermediate directory...
14:23:31 miketesting911: Done in 1 sec(s).
14:23:31 miketesting911: Source directory     : /tmp/8dc294c9322c9f9
14:23:31 miketesting911: Destination directory: /home/site/wwwroot
14:23:31 miketesting911: Downloading and extracting 'python' version '3.9.18' to '/tmp/oryx/platforms/python/3.9.18'...
14:23:31 miketesting911: Detected image debian flavor: buster.
14:23:32 miketesting911: Downloaded in 1 sec(s).
14:23:32 miketesting911: Verifying checksum...
14:23:32 miketesting911: Extracting contents...
14:23:45 miketesting911: performing sha512 checksum for: python...
14:23:47 miketesting911: Done in 16 sec(s).
14:23:47 miketesting911: Python Version: /tmp/oryx/platforms/python/3.9.18/bin/python3.9
14:23:47 miketesting911: Creating directory for command manifest file if it does not exist
14:23:47 miketesting911: Removing existing manifest file
14:23:47 miketesting911: Python Virtual Environment: antenv
14:23:47 miketesting911: Creating virtual environment...
14:24:06 miketesting911: Activating virtual environment...
14:24:06 miketesting911: Running pip install...

**Comment by alexweininger** [comment]
@KartikeyBartwal can you create a new issue on the https://github.com/microsoft/vscode-azureappservice repository?
